version: '3'
services:
  php:
    build: "./docker/php-fpm"
    volumes:
        - ./:/var/www/app
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  psql:
      image: postgres:9.5.14
      ports:
       - "5432:5432"
      environment:
       - POSTGRES_PASSWORD=password
       - POSTGRES_USER=user
       - POSTGRES_DB=db
       - PGDATA=/var/lib/postgresql/data/pgdata
      volumes:
       - psql-data:/var/lib/postgresql/data/pgdata
volumes:
  mysql-data:
  psql-data:
